spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true

campsite:
  reservation:
    max-period: 3
  search:
    max-period: 365

---

spring:
  profiles: docker
  redis:
    host: redis
  jpa:
    show-sql: false

