spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
campsite:
  reservation:
    max-period: 3
  search:
    max-period: 365

---

spring:
  profiles: docker
  redis:
    host: redis
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
